# Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [3]:
import numpy as np

In [4]:
def generate_vandermonde_matrix(vector, power, increasing=True):
    length = len(vector)
    matrix = np.empty((length, power))
    if increasing:
        for i in range(power):
            matrix[:, i] = np.power(vector, i)
    else:
        for i in range(power):
            matrix[:, i] = np.power(vector, power-i-1)
    return matrix

In [7]:
np.set_printoptions(suppress=True)
input_vector = np.array([2, 3, 4])
output_matrix = generate_vandermonde_matrix(input_vector, 6, increasing=False)
print(output_matrix)

[[  32.   16.    8.    4.    2.    1.]
 [ 243.   81.   27.    9.    3.    1.]
 [1024.  256.   64.   16.    4.    1.]]


In [11]:
def moving_average(seq, kernel):
    num_values = len(seq)
    moving_averages = []
    
    for i in range(num_values - kernel + 1):
        window = seq[i:i+kernel]
        average = sum(window) / kernel
        moving_averages.append(average)
    
    return moving_averages

In [12]:
sequence = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
window_size = 4

averages = moving_average(sequence, window_size)
print(averages)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]


# Question: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [13]:
lst=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window_size=3
averages = moving_average(lst, window_size)
print(averages)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
